general.import = [
  #"~/.config/alacritty/themes/catppuccin-latte.toml"
  "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[env]
TERM = "alacritty"

[window]
padding = { x = 10, y = 10 }

[font]
normal = { family = "FiraCode Nerd Font" }
# normal = { family = "JetBrainsMono Nerd Font" }
size = 11

[cursor]
style = { shape = "underline", blinking = "always" }
unfocused_hollow = false

[mouse]
hide_when_typing = true
