add_newline = false

format = """
$sudo\
$directory\
$git_branch\
$git_commit\
$git_status\
$character
"""

right_format = """
$cmd_duration\
$python\
$lua\
$rust\
$go\
$nodejs
"""

palette = "oldworld"

[sudo]
format = "${symbol}"
symbol = ' '
disabled = false

[character]
success_symbol = '[](bold blue) '
error_symbol = '[󰅙](bold red) '

[cmd_duration]
min_time = 1
format = "(fg:bg bg:bg)[](fg:purple bg:bg)[ $duration](fg:bg bg:purple)[](fg:purple bg:none) "
style = "fg:purple bg:bg"

[directory]
format = "(fg:bg bg:bg)[](fg:magenta bg:bg)[  $path](fg:bg bg:magenta italic)[](fg:magenta bg:none) "
style = "fg:#d9d7d6 bg:bg"
truncation_length = 1
truncate_to_repo = true
truncation_symbol = '…/'

[directory.substitutions]
"~" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = "[ ](fg:purple)[$branch](fg:fg) "

[git_status]
staged = '[++$count](fg:green)'
format = '\[[$all_status](fg:cyan)\] '

[python]
format = "(fg:bg bg:bg)[](fg:green bg:bg)[${symbol}(${virtualenv})-(${version})](fg:bg bg:green)[](fg:green bg:none) "
style = "fg:green bg:bg"
version_format = "${major}${minor}"
symbol = '󰌠 '

[lua]
format = "(fg:bg bg:bg)[](fg:blue bg:bg)[$symbol$version](fg:bg bg:blue)[](fg:blue bg:none) "
style = "fg:blue bg:bg"
symbol = ' '

[rust]
format = "(fg:bg bg:bg)[](fg:red bg:bg)[$symbol$version](fg:bg bg:red)[](fg:red bg:none) "
style = "fg:red bg:bg"
symbol = ' '

[nodejs]
format = "(fg:bg bg:bg)[](fg:green bg:bg)[$symbol$version](fg:bg bg:green)[](fg:green bg:none) "
style = "fg:green bg:bg"
symbol = '󰎙 '

[golang]
format = "(fg:bg bg:bg)[](fg:blue bg:bg)[$symbol$version-$name](fg:bg bg:blue)[](fg:blue bg:none) "
style = "fg:blue bg:bg"
symbol = ' '

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.oldworld]
magenta = "#e29eca"
purple = "#aca1cf"
red = "#ea83a5"
orange = "#f5a191"
yellow = "#e6b99d"
green = "#90b99f"
cyan = "#85b5ba"
blue = "#92a2d5"
fg = "#c9c7cd"
bg = "#161617"
